


######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: /android
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html

#Author config
author:
    name: 赵井华
    email: shaipxiang@163.com
    imageLink: http://img01.muzhiwan.com/2011/10/25/4ea61cf2e3bd9.jpg
    simpleIntro: 我是 DroidHua <p>专注于手机开发工作，热衷于新技术的研究，现工作于易华录·北京</p>
    detailIntro:
      <p>专注于手机开发工作，热衷于新技术的研究，致力于成为一名优秀的安卓工程师，现工作于易华录·北京。</p>
#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-github
    url: https://github.com
  - class: icon-android
    url: https://developer.android.com/reference/packages.html
  - class: icon-twitter
    url: http://www.jianshu.com
  - class: icon-weibo
    url: http://weibo.com
  - class: icon-facebook
    url: http://www.facebook.com
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 张明云
      url: https://zhuanlan.zhihu.com/zmywly8866
    - text: Trinea
      url: https://github.com/Trinea
    - text: Blankj
      url: http://www.jianshu.com/u/46702d5c6978
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#comment config
disqus:
  config: false
  id: minixalpha


#################################### global configure #######################################

username: shaipxiang
baseurl: /android
markdown: redcarpet
safe: false
highlighter: pygments
title: DroidHua
description: 博学之,审问之,慎思之,明辨之,笃行之
theme: kunka
disqusname: shaipxiang

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
